marquez_raw = """
Esta es, incrédulos del mundo entero, la verídica historia de la Mamá Grande, soberana absoluta del reino de Macondo, que vivió en función de dominio durante 92 años y murió en olor de santidad un martes del setiembre pasado, y a cuyos funerales vino el sumo pontífice.

Ahora que la nación sacudida en sus entrañas ha recobrado el equilibrio; ahora que los gaiteros de San Jacinto, los contrabandistas de la Guajira, los arroceros del Sinú, las prostitutas de Guacamayal, los hechiceros de la Sierpe y los bananeros de Aracataca han colgado sus toldos para restablecerse de la extenuante vigilia, y que han recuperado la serenidad y vuelto a tomar posesión de sus estados el presidente de la república y sus ministros y todos aquellos que representaron al poder público y a las potencias sobrenaturales en la más espléndida ocasión funeraria que registren los anales históricos; ahora que el sumo pontífice ha subido a los Cielos en cuerpo y alma, y que es imposible transitar en Macondo a causa de las botellas vacías, las colillas de cigarrillos, los huesos roídos, las latas y trapos y excrementos que dejó la muchedumbre que vino al entierro, ahora es la hora de recostar un taburete a la puerta de la calle y empezar a contar desde el principio los pormenores de esta conmoción nacional, antes de que tengan tiempo de llegar los historiadores.

Hace catorce semanas, después de interminables noches de cataplasmas, sinapismos y ventosas, demolida por la delirante agonía, la Mamá Grande ordenó que la sentaran en su viejo mecedor de bejuco para expresar su última voluntad. Era el único requisito que le hacía falta para morir. Aquella mañana, por intermedio del padre Antonio Isabel, había arreglado los negocios de su alma, y solo le faltaba arreglar los de sus arcas con los nueve sobrinos, sus herederos universales, que velaban en torno al lecho. El párroco, hablando solo y a punto de cumplir cien años, permanecía en el cuarto. Se habían necesitado diez hombres para subirlo hasta la alcoba de la Mamá Grande, y se había decidido que allí permaneciera para no tener que bajarlo y volverlo a subir en el minuto final.

Nicanor, el sobrino mayor, titánico y montaraz, vestido de caqui, botas con espuelas y un revólver calibre 38, cañón largo, ajustado bajo la camisa, fue en busca del notario. La enorme mansión de dos plantas, olorosa a melaza y a orégano, con sus oscuros aposentos atiborrados de arcones y cachivaches de cuatro generaciones convertidas en polvo, se había paralizado desde la semana anterior a la expectativa de aquel momento. En el profundo corredor central, con garfios en las paredes donde en otro tiempo se colgaron cerdos desollados y se desangraban venados en los soñolientos domingos de agosto, los peones dormían amontonados sobre sacos de sal y útiles de labranza, esperando la orden de ensillar las bestias para divulgar la mala noticia en el ámbito de la hacienda desmedida. El resto de la familia estaba en la sala. Las mujeres lívidas, desangradas por la herencia y la vigilia, guardaban un luto cerrado que era una suma de incontables lutos superpuestos. La rigidez matriarcal de la Mamá Grande había cercado su fortuna y su apellido con una alambrada sacramental, dentro de la cual los tíos se casaban con las hijas de las sobrinas, y los primos con las tías, y los hermanos con las cuñadas, hasta formar una intrincada maraña de consanguinidad que convirtió la procreación en un círculo vicioso. Solo Magdalena, la menor de las sobrinas, logró escapar al cerco; aterrorizada por las alucinaciones se hizo exorcizar por el padre Antonio Isabel, se rapó la cabeza y renunció a las glorias y vanidades del mundo en el noviciado de la Prefectura Apostólica. Al margen de la familia oficial y en ejercicio del derecho de pernada, los varones habían fecundado hatos, veredas y caseríos con toda una descendencia bastarda, que circulaba entre la servidumbre sin apellidos a título de ahijados, dependientes, favoritos y protegidos de la Mamá Grande.

La inminencia de la muerte removió la extenuante expectativa. La voz de la moribunda, acostumbrada al homenaje y a la obediencia, no fue más sonora que un bajo de órgano en la pieza cerrada, pero resonó en los más apartados rincones de la hacienda. Nadie era indiferente a esa muerte. Durante el presente siglo, la Mamá Grande había sido el centro de gravedad de Macondo, como sus hermanos, sus padres y los padres de sus padres lo fueron en el pasado, en una hegemonía que colmaba dos siglos. La aldea se fundó alrededor de su apellido. Nadie conocía el origen ni los límites ni el valor real del patrimonio, pero todo el mundo se había acostumbrado a creer que la Mamá Grande era dueña de las aguas corrientes y estancadas, llovidas y por llover, y de los caminos vecinales, los postes del telégrafo, los años bisiestos y el calor, y que tenía además un derecho heredado sobre vida y haciendas. Cuando se sentaba a tomar el fresco de la tarde en el balcón de su casa, con todo el peso de sus vísceras y su autoridad aplastado en su viejo mecedor de bejuco, parecía en verdad infinitamente rica y poderosa, la matrona más rica y poderosa del mundo.

A nadie se le había ocurrido pensar que la Mamá Grande fuera mortal, salvo a los miembros de su tribu, y a ella misma, aguijoneada por las premoniciones seniles del padre Antonio Isabel. Pero ella confiaba en que viviría más de 100 años, como su abuela materna, que en la guerra de 1875 se enfrentó a una patrulla del coronel Aureliano Buendía, atrincherada en la cocina de la hacienda. Solo en abril de este año comprendió la Mamá Grande que Dios no le concedería el privilegio de liquidar personalmente, en franca refriega, a una horda de masones federalistas.

En la primera semana de dolores el médico de la familia la entretuvo con cataplasmas de mostaza y calcetines de lana. Era un médico hereditario, laureado en Montpellier, contrario por convicción filosófica a los progresos de su ciencia, a quien la Mamá Grande había concedido la prebenda de que se impidiera en Macondo el establecimiento de otros médicos. En un tiempo recorría el pueblo a caballo, visitando a los lúgubres enfermos del atardecer, y la naturaleza le concedió el privilegio de ser padre de numerosos hijos ajenos. Pero la artritis le anquilosó en un chinchorro, y terminó por atender a sus pacientes sin visitarlos, por medio de suposiciones, correveidiles y recados. Requerido por la Mamá Grande atravesó la plaza en pijama, apoyado en dos bastones, y se instaló en la alcoba de la enferma. Solo cuando comprendió que la Mamá Grande agonizaba, hizo llevar un arca con pomos de porcelana marcados en latín y durante tres semanas embadurnó a la moribunda por dentro y por fuera con toda suerte de emplastos académicos, julepes magníficos y supositorios magistrales. Después le aplicó sapos ahumados en el sitio del dolor y sanguijuelas en los riñones, hasta la madrugada de ese día en que tuvo que enfrentarse a la disyuntiva de hacerla sangrar por el barbero o exorcizar por el padre Antonio Isabel.

Nicanor mandó a buscar al párroco. Sus diez hombres mejores lo llevaron desde la casa cural hasta el dormitorio de la Mamá Grande, sentado en su crujiente mecedor de mimbre bajo el mohoso palio de las grandes ocasiones. La campanilla del Viático en el tibio amanecer de setiembre fue la primera notificación a los habitantes de Macondo. Cuando salió el sol, la placita frente a la casa de la Mamá Grande parecía una feria rural.

Era como el recuerdo de otra época. Hasta cuando cumplió los 70, la Mamá Grande celebró su cumpleaños con las ferias más prolongadas y tumultuosas de que se tenga memoria. Se ponían damajuanas de aguardiente a disposición del pueblo, se sacrificaban reses en la plaza pública, y una banda de músicos instalada sobre una mesa tocaba sin tregua durante tres días. Bajo los almendros polvorientos donde la primera semana del siglo acamparon las legiones del coronel Aureliano Buendía, se ponían ventas de masato, bollos, morcillas, chicharrones, empanadas, butifarras, caribañolas, pandeyuca, almojábanas, buñuelos, arepuelas, hojaldres, longanizas, mondongos, cocadas, guarapo, entre todo género de menudencias, chucherías, baratijas y cacharros, y peleas de gallos y juegos de lotería. En medio de la confusión de la muchedumbre alborotada, se vendían estampas y escapularios con la imagen de la Mamá Grande.

Las festividades comenzaban la antevíspera y terminaban el día del cumpleaños, con un estruendo de fuegos artificiales y un baile familiar en la casa de la Mamá Grande. Los selectos invitados y los miembros legítimos de la familia, generosamente servidos por la bastardía, bailaban al compás de la vieja pianola equipada con rollos de moda. La Mamá Grande presidía la fiesta desde el fondo del salón, en una poltrona con almohadas de lino, impartiendo discretas instrucciones con su diestra adornada de anillos en todos los dedos. A veces en complicidad con los enamorados pero casi siempre aconsejada por su propia inspiración, aquella noche concertaba los matrimonios del año entrante. Para clausurar el jubileo, la Mamá Grande salía al balcón adornado con diademas y faroles de papel, y arrojaba monedas a la muchedumbre.

Aquella tradición se había interrumpido, en parte por los duelos sucesivos de la familia, y en parte por la incertidumbre política de los últimos tiempos. Las nuevas generaciones no asistieron sino de oídas a aquellas manifestaciones de esplendor. No alcanzaron a ver a la Mamá Grande en la misa mayor, abanicada por algún miembro de la autoridad civil, disfrutando del privilegio de no arrodillarse ni en el instante de la elevación para no estropear su saya de volantes holandeses y sus almidonados pollerines de olán. Los ancianos recordaban como una alucinación de la juventud los doscientos metros de esteras que se tendieron desde la casa solariega hasta el altar mayor, la tarde en que María del Rosario Castañeda y Montero asistió a los funerales de su padre, y regresó por la calle esterada investida de su nueva e irradiante dignidad, a los 22 años, convertida en la Mamá Grande. Aquella visión medieval pertenecía entonces no solo al pasado de la familia, sino al pasado de la nación. Cada vez más imprecisa y remota, visible apenas en su balcón sofocado entonces por los geranios en las tardes de calor, la Mamá Grande se esfumaba en su propia leyenda. Su autoridad se ejercía a través de Nicanor. Existía la promesa tácita, formulada por la tradición, de que el día en que la Mamá Grande lacrara su testamento, los herederos decretarían tres noches de jolgorios públicos. Pero se sabía asimismo que ella había decidido no expresar su voluntad última hasta pocas horas antes de morir, y nadie pensaba seriamente en la posibilidad de que la Mamá Grande fuera mortal. Solo esa madrugada, despertados por los cencerros del Viático, los habitantes de Macondo se convencieron de que la Mamá Grande no solo era mortal, sino que se estaba muriendo.

Su hora era llegada. En su cama de lienzo, embadurnada de áloes hasta las orejas, bajo la marquesina de polvorienta espumilla, apenas se adivinaba la vida en la tenue respiración de sus tetas matriarcales. La Mamá Grande, que hasta los cincuenta años rechazó a los más apasionados pretendientes, y que fue dotada por la naturaleza para amamantar ella sola a toda su especie, agonizaba virgen y sin hijos. En el momento de la extremaunción, el padre Antonio Isabel tuvo que pedir ayuda para aplicarle los óleos en la palma de las manos, pues desde el principio de su agonía la Mamá Grande tenía los puños cerrados. De nada valió el concurso de las sobrinas. En el forcejeo, por primera vez en una semana, la moribunda apretó contra su pecho la mano constelada de piedras preciosas, y fijó en las sobrinas su mirada sin color, diciendo: “Salteadoras.” Luego vio al padre Antonio Isabel en indumentaria litúrgica y al monaguillo con los instrumentos sacramentales, y murmuró con una convicción apacible: “Me estoy muriendo.” Entonces se quitó el anillo con el Diamante Mayor y se lo dio a Magdalena, la novicia, a quien correspondía por ser la heredera menor. Aquel era el final de una tradición: Magdalena había renunciado a su herencia en favor de la Iglesia.

Al amanecer, la Mamá Grande pidió que la dejaran a solas con Nicanor para impartir sus últimas instrucciones. Durante media hora, con perfecto dominio de sus facultades, se informó de la marcha de los negocios. Hizo formulaciones especiales sobre el destino de su cadáver, y se ocupó por último de las velaciones. “Tienes que estar con los ojos abiertos”, dijo. “Guarda bajo llave todas las cosas de valor, pues mucha gente no viene a los velorios sino a robar.” Un momento después, a solas con el párroco, hizo una confesión dispendiosa, sincera y detallada, y comulgó más tarde en presencia de los sobrinos. Entonces fue cuando pidió que la sentaran en el mecedor de bejuco para expresar su última voluntad.

Nicanor había preparado, en veinticuatro folios escritos con letra muy clara, una escrupulosa relación de sus bienes. Respirando apaciblemente, con el médico y el padre Antonio Isabel por testigos, la Mamá Grande dictó al notario la lista de sus propiedades, fuente suprema y única de su grandeza y autoridad. Reducido a sus proporciones reales, el patrimonio físico se reducía a tres encomiendas adjudicadas por Cédula Real durante la Colonia, y que con el transcurso del tiempo, en virtud de intrincados matrimonios de conveniencia, se habían acumulado bajo el dominio de la Mamá Grande. En ese territorio ocioso, sin límites definidos, que abarcaba cinco municipios y en el cual no se sembró nunca un solo grano por cuenta de los propietarios, vivían a título de arrendatarias 352 familias. Todos los años, en vísperas de su onomástico, la Mamá Grande ejercía el único acto de dominio que había impedido el regreso de las tierras al estado: el cobro de los arrendamientos. Sentada en el corredor interior de su casa, ella recibía personalmente el pago del derecho de habitar en sus tierr�s, como durante más de un siglo lo recibieron sus antepasados de los antepasados de los arrendatarios. Pasados los tres días de la recolección, el patio estaba atiborrado de cerdos, pavos y gallinas, y de los diezmos y primicias sobre los frutos de la tierra que se depositaban allí en calidad de regalo. En realidad, esa era la única cosecha que jamás recogió la familia de un territorio muerto desde sus orígenes, calculado a primera vista en 100 000 hectáreas. Pero las circunstancias históricas habían dispuesto que dentro de esos límites crecieran y prosperaran las seis poblaciones del distrito de Macondo, incluso la cabecera del municipio, de manera que todo el que habitara una casa no tenía más derecho de propiedad del que le correspondía sobre los materiales, pues la tierra pertenecía a la Mamá Grande y a ella se pagaba el alquiler, como tenía que pagarlo el gobierno por el uso que los ciudadanos hacían en las calles.

En los alrededores de los caseríos, merodeaba un número nunca contado y menos atendido de animales herrados en los cuartos traseros con la forma de un candado. Ese hierro hereditario, que más por el desorden que por la cantidad se había hecho familiar en remotos departamentos donde llegaban en verano, muertas de sed, las reses desperdigadas, era uno de los más sólidos soportes de la leyenda. Por razones que nadie se había detenido a explicar, las extensas caballerizas de la casa se habían vaciado progresivamente desde la última guerra civil, y en los últimos tiempos se habían instalado en ellas trapiches de caña, corrales de ordeño, y una piladora de arroz.

Aparte de lo enumerado, se hacía constar en el testamento la existencia de tres vasijas de morrocotas enterradas en algún lugar de la casa durante la guerra de Independencia, que no habían sido halladas en periódicas y laboriosas excavaciones. Con el derecho de continuar la explotación de la tierra arrendada y de percibir los diezmos y primicias y toda clase de dádivas extraordinarias, los herederos recibían un plano levantado de generación en generación, y por cada generación perfeccionado, que facilitaba el hallazgo del tesoro enterrado.

La Mamá Grande necesitó tres horas para enumerar sus asuntos terrenales. En la sofocación de la alcoba, la voz de la moribunda parecía dignificar en su sitio cada cosa enumerada. Cuando estampó su firma, balbuciente, y debajo estamparon la suya los testigos, un temblor secreto sacudió el corazón de las muchedumbres que empezaban a concentrarse frente a la casa, a la sombra de los almendros polvorientos.

Solo faltaba entonces la enumeración minuciosa de los bienes morales. Haciendo un esfuerzo supremo -el mismo que hicieron sus antepasados antes de morir para asegurar el predominio de su especie- la Mamá Grande se irguió sobre sus nalgas monumentales, y con voz dominante y sincera, abandonada a su memoria, dictó al notario la lista de su patrimonio invisible:

La riqueza del subsuelo, las aguas territoriales, los colores de la bandera, la soberanía nacional, los partidos tradicionales, los derechos del hombre, las libertades ciudadanas, el primer magistrado, la segunda instancia, el tercer debate, las cartas de recomendación, las constancias históricas, las elecciones libres, las reinas de la belleza, los discursos trascendentales, las grandiosas manifestaciones, las distinguidas señoritas, los correctos caballeros, los pundonorosos militares, su señoría ilustrísima, la corte suprema de justicia, los artículos de prohibida importación, las damas liberales, el problema de la carne, la pureza del lenguaje, los ejemplos para el mundo, el orden jurídico, la prensa libre pero responsable, la Atenas sudamericana, la opinión pública, las lecciones democráticas, la moral cristiana, la escasez de divisas, el derecho de asilo, el peligro comunista, la nave del estado, la carestía de la vida, las tradiciones republicanas, las clases desfavorecidas, los mensajes de adhesión.

No alcanzó a terminar. La laboriosa enumeración tronchó su último viaje. Ahogándose en el mare mágnum de fórmulas abstractas que durante dos siglos constituyeron la justificación moral del poderío de la familia, la Mamá Grande emitió un sonoro eructo, y expiró.

Los habitantes de la capital remota y sombría vieron esa tarde el retrato de una mujer de veinte años en la primera página de las ediciones extraordinarias, y pensaron que era una nueva reina de la belleza. La Mamá Grande vivía otra vez la momentánea juventud de su fotografía, ampliada a cuatro columnas y con retoques urgentes, su abundante cabellera recogida a lo alto del cráneo con un peine de marfil, y una diadema sobre la gola de encajes. Aquella imagen, captada por un fotógrafo ambulante que pasó por Macondo a principios de siglo y archivada por los periódicos durante muchos años en la división de personajes desconocidos, estaba destinada a perdurar en la memoria de las generaciones futuras. En los autobuses decrépitos, en los ascensores de los ministerios, en los lúgubres salones de té forrados de pálidas colgaduras, se susurró con veneración y respeto de la autoridad muerta en su distrito de calor y malaria, cuyo nombre se ignoraba en el resto del país hacía pocas horas, antes de ser consagrado por la palabra impresa. Una llovizna menuda cubría de recelo y de verdín a los transeúntes. Las campanas de todas las iglesias tocaban a muerto. El presidente de la república, sorprendido por la noticia cuando se dirigía al acto de graduación de los nuevos cadetes, sugirió al ministro de la guerra, en una nota escrita de su puño y letra en el revés del telegrama, que concluyera su discurso con un minuto de silencio en homenaje a la Mamá Grande.

El orden social había sido rozado por la muerte. El propio presidente de la república, a quien los sentimientos urbanos llegaban como a través de un filtro de purificación, alcanzó a percibir desde su automóvil en una visión instantánea pero hasta un cierto punto brutal, la silenciosa consternación de la ciudad. Solo permanecían abiertos algunos cafetines de mala muerte, y la Catedral Metropolitana, dispuesta para nueve días de honras fúnebres. En el Capitolio Nacional, donde los mendigos envueltos en papeles dormían al amparo de columnas dóricas y taciturnas estatuas de presidentes muertos, las luces del Congreso estaban encendidas. Cuando el primer mandatario entró a su despacho, conmovido por la visión de la capital enlutada, sus ministros lo esperaban vestidos de tafetán funerario, de pie, más solemnes y pálidos que de costumbre.

Los acontecimientos de aquella noche y las siguientes serían más tarde definidos como una lección histórica. No solo por el espíritu cristiano que inspiró a los más elevados personeros del poder público, sino por la abnegación con que se conciliaron intereses disímiles y criterios contrapuestos, en el propósito común de enterrar un cadáver ilustre. Durante muchos años la Mamá Grande había garantizado la paz social y la concordia política de su imperio, en virtud de los tres baúles de cédulas electorales falsas que formaban parte de su patrimonio secreto. Los varones de la servidumbre, sus protegidos y arrendatarios, mayores y menores de edad, ejercitaban no solo su propio derecho de sufragio, sino también el de los electores muertos en un siglo. Ella era la prioridad del poder tradicional sobre la autoridad transitoria, el predominio de la clase sobre la plebe, la trascendencia de la sabiduría divina sobre la improvisación mortal. En tiempos pacíficos, su voluntad hegemónica acordaba y desacordaba canonjías, prebendas y sinecuras, y velaba por el bienestar de los asociados así tuviera para lograrlo que recurrir a la trapisonda o al fraude electoral. En tiempos tormentosos, la Mamá Grande contribuyó en secreto para armar a sus partidarios, y socorrió en público a sus víctimas. Aquel celo patriótico la acreditaba para los más altos honores.

El presidente de la república no había tenido necesidad de recurrir a sus consejeros para medir el peso de su responsabilidad. Entre la sala de audiencias de Palacio y el patiecito adoquinado que sirvió de cochera a los virreyes, mediaba un jardín interior de cipreses oscuros donde un fraile portugués se ahorcó por amor en las postrimerías de la Colonia. A pesar de su ruidoso aparato de oficiales condecorados, el presidente no podía reprimir un ligero temblor de incertidumbre cuando pasaba por ese lugar después del crepúsculo. Pero aquella noche, el estremecimiento tuvo la fuerza de una premonición. Entonces adquirió plena conciencia de su destino histórico, y decretó nueve días de duelo nacional, y honores póstumos a la Mamá Grande en la categoría de heroína muerta por la patria en el campo de batalla. Como lo expresó en la dramática alocución que aquella madrugada dirigió a sus compatriotas a través de la cadena nacional de radio y televisión, el primer magistrado de la nación confiaba en que los funerales de la Mamá Grande constituyeran un nuevo ejemplo para el mundo.

Tan altos propósitos debían tropezar sin embargo con graves inconvenientes. La estructura jurídica del país, construida por remotos ascendientes de la Mamá Grande, no estaba preparada para acontecimientos como los que empezaban a producirse. Sabios doctores de la ley, probados alquimistas del derecho ahondaron en hermenéuticas y silogismos, en busca de la fórmula que permitiera al presidente de la república asistir a los funerales. Se vivieron días de sobresalto en las altas esferas de la política, el clero y las finanzas. En el vasto hemiciclo del Congreso, enrarecido por un siglo de legislación abstracta, entre óleos de próceres nacionales y bustos de pensadores griegos, la evocación de la Mamá Grande alcanzó proporciones insospechables, mientras su cadáver se llenaba de burbujas en el duro setiembre de Macondo. Por primera vez se habló de ella y se la concibió sin su mecedor de bejuco, sus sopores a las dos de la tarde y sus cataplasmas de mostaza, y se la vio pura y sin edad, destilada por la leyenda.

Horas interminables se llenaron de palabras, palabras, palabras que repercutían en el ámbito de la república, aprestigiadas por los altavoces de la letra impresa. Hasta que alguien dotado de sentido de la realidad en aquella asamblea de jurisconsultos asépticos, interrumpió el blablablá histórico para recordar que el cadáver de la Mamá Grande esperaba la decisión a 40 grados a la sombra. Nadie se inmutó frente a aquella irrupción del sentido común en la atmósfera pura de la ley escrita. Se impartieron órdenes para que fuera embalsamado el cadáver, mientras se encontraban fórmulas, se conciliaban pareceres o se hacían enmiendas constitucionales que permitieran al presidente de la república asistir al entierro.

Tanto se había parlado, que los parloteos transpusieron las fronteras, traspasaron el océano y atravesaron como un presentimiento las habitaciones pontificias de Castelgandolfo. Repuesto de la modorra del ferragosto reciente, el sumo pontífice estaba en la ventana, viendo en el lago sumergirse los buzos que buscaban la cabeza de la doncella decapitada. En las últimas semanas los periódicos de la tarde no se habían ocupado de otra cosa, y el sumo pontífice no podía ser indiferente a un enigma planteado a tan corta distancia de su residencia de verano. Pero aquella tarde, en una sustitución imprevista, los periódicos cambiaron las fotografías de las posibles víctimas por la de una sola mujer de veinte años, señalada con una blonda de luto. “La Mamá Grande”, exclamó el sumo pontífice, reconociendo al instante el borroso daguerrotipo que muchos años antes le había sido ofrendado con ocasión de su ascenso a la Silla de San Pedro. “La Mamá Grande”, exclamaron a coro en sus habitaciones privadas los miembros del Colegio Cardenalicio, y por tercera vez en veinte siglos hubo una hora de desconciertos, sofoquines y correndillas en el imperio sin límites de la cristiandad, hasta que el sumo pontífice estuvo instalado en su larga góndola negra, rumbo a los fantásticos y remotos funerales de la Mamá Grande.

Detrás quedaron los luminosos sembrados de melocotones, la Vía Apia Antica con tibias actrices de cine dorándose en las terrazas sin todavía tener noticias de la conmoción, y después el sombrío promontorio del Castelsantangelo en el horizonte del Tíber. Al crepúsculo los profundos dobles de la Basílica de San Pedro se entreveraron con los bronces cuarteados de Macondo. Desde su toldo sofocante, a través de los caños intrincados y las ciénagas sigilosas que marcaban el límite del Imperio Romano y los hatos de la Mamá Grande, el sumo pontífice oyó toda la noche la bullaranga de los monos alborotados por el paso de las muchedumbres. En su itinerario nocturno la canoa pontificia se había ido llenando de costales de yuca, racimos de plátanos verdes y huacales de gallina, y de hombres y mujeres que abandonaban sus ocupaciones habituales para tentar fortuna con cosas de vender en los funerales de la Mamá Grande. Su santidad padeció esa noche, por primera vez en la historia de la Iglesia, la fiebre de la vigilia y el tormento de los zancudos. Pero el prodigioso amanecer sobre los dominios de la Gran Vieja, la visión primigenia del reino de la balsamina y de la iguana, borraron de su memoria los padecimientos del viaje y lo compensaron del sacrificio.

Nicanor había sido despertado por tres golpes en la puerta que anunciaban el arribo inminente de su santidad. La muerte había tomado posesión de la casa. Inspirados por sucesivas y apremiantes alocuciones presidenciales, por las febriles controversias de los parlamentarios que habían perdido la voz y continuaban entendiéndose por medio de signos convencionales, hombres y congregaciones de todo el mundo se desentendieron de sus asuntos y colmaron con su presencia los oscuros corredores, los atiborrados pasadizos, las asfixiantes buhardas, y quienes llegaron con retardo se treparon y acomodaron del mejor modo en barbacanas, palenques, atalayas, maderámenes y matacanes. En el salón central, momificándose en espera de las grandes decisiones, yacía el cadáver de la Mamá Grande, bajo un estremecido promontorio de telegramas. Extenuados por las lágrimas, los nueve sobrinos velaban el cuerpo en un éxtasis de vigilancia recíproca.

Aún debió el universo prolongar el acecho durante muchos días. En el salón del consejo municipal, acondicionado con cuatro taburetes de cuero, una tinaja de agua filtrada y una hamaca de lampazo, el sumo pontífice padeció un insomnio sudoroso, entreteniéndose con la lectura de memoriales y disposiciones administrativas en las dilatadas noches sofocantes. Durante el día, repartía caramelos italianos a los niños que se acercaban a verlo por la ventana, y almorzaba bajo la pérgola de astromelias con el padre Antonio Isabel, y ocasionalmente con Nicanor. Así vivió semanas interminables y meses alargados por la expectativa y el calor, hasta que Pastor Pastrana se plantó con su redoblante en el centro de la plaza y leyó el bando de la decisión. Se declaraba turbado el orden público, tarrataplán, y el presidente de la república, tarrataplán, disponía de las facultades extraordinarias, tarrataplán, que le permitían asistir a los funerales de la Mamá Grande, tarrataplán, rataplán, plan, plan.

El gran día era venido. En las calles congestionadas de ruletas, fritangas y mesas de lotería, y hombres con culebras enrolladas en el cuello que pregonaban el bálsamo definitivo para curar la erisipela y asegurar la vida eterna; en la placita abigarrada donde las muchedumbres habían colgado sus toldos y desenrollado sus petates, apuestos ballesteros despejaron el paso a la autoridad. Allí estaban, en espera del momento supremo, las lavanderas del San Jorge, los pescadores de perla del Cabo de Vela, los atarrayeros de Ciénega, los camaroneros de Tasajera, los brujos de la Mojana, los salineros de Manaure, los acordeoneros de Valledupar, los chalanes de Ayapel, los papayeros de San Pelayo, los mamadores de gallo de La Cueva, los improvisadores de las Sabanas de Bolívar, los camajanes de Rebolo, los bogas del Magdalena, los tinterillos de Mompox, además de los que se enumeran al principio de esta crónica, y muchos otros. Hasta los veteranos del coronel Aureliano Buendía -el duque de Marlborough a la cabeza, con su atuendo de pieles y uñas y dientes de tigre- se sobrepusieron a su rencor centenario por la Mamá Grande y los de su especie, y vinieron a los funerales, para solicitar del presidente de la república el pago de las pensiones de guerra que esperaban desde hacía sesenta años.

Poco antes de las once, la muchedumbre delirante que se asfixiaba al sol, contenida por una élite imperturbable de guerreros uniformados de dormanes guarnecidos y espumosos morriones, lanzó un poderoso rugido de júbilo. Dignos, solemnes en sus sacolevas y chisteras, el presidente de la república y sus ministros, las comisiones del parlamento, la corte suprema de justicia, el consejo de estado, los partidos tradicionales y el clero, y los representantes de la banca, el comercio y la industria, hicieron su aparición por la esquina de la telegrafía. Calvo y rechoncho, el anciano y enfermo presidente de la república desfiló frente a los ojos atónitos de las muchedumbres que lo habían investido sin conocerlo y que solo ahora podían dar un testimonio verídico de su existencia. Entre los arzobispos extenuados por la gravedad de su ministerio y los militares de robusto tórax acorazado de insignias, el primer magistrado de la nación transpiraba el hálito inconfundible del poder.

En segundo término, en un sereno transcurso de crespones luctuosos, desfilaban las reinas nacionales de todas las cosas habidas y por haber. Por primera vez desprovistas del esplendor terrenal, allí pasaron, precedidas de la reina universal, la reina del mango de hilacha, la reina de la ahuyama verde, la reina del guineo manzano, la reina de la yuca harinosa, la reina de la guayaba perulera, la reina del coco de agua, la reina del frijol de cabecita negra, la reina de 426 kilómetros de sartales de huevos de iguana, y todas las que se omiten por no hacer interminables estas crónicas.

En su féretro con vueltas de púrpura, separada de la realidad por ocho torniquetes de cobre, la Mamá Grande estaba entonces demasiado embebida en su eternidad de formaldehído para darse cuenta de la magnitud de su grandeza. Todo el esplendor con que ella había soñado en el balcón de su casa durante las vigilias del calor, se cumplió con aquellas cuarenta y ocho gloriosas en que todos los símbolos de la época rindieron homenaje a su memoria. El propio sumo pontífice, a quien ella imaginó en sus delirios suspendido en una carroza resplandeciente sobre los jardines del Vaticano, se sobrepuso al calor con un abanico de palma trenzada y honró con su dignidad suprema los funerales más grandes del mundo.

Obnubilado por el espectáculo del poder, el populacho no determinó el ávido aleteo que ocurrió en el caballete de la casa cuando se impuso el acuerdo en la disputa de los ilustres, y se sacó el catafalco a la calle en hombros de los más ilustres. Nadie vio la vigilante sombra de gallinazos que siguió al cortejo por las ardientes callecitas de Macondo, ni reparó que al paso de los ilustres estas se iban cubriendo de un pestilente rastro de desperdicios. Nadie advirtió que los sobrinos, ahijados, sirvientes y protegidos de la Mamá Grande cerraron las puertas tan pronto como sacaron el cadáver, y desmontaron las puertas, desenclavaron las tablas y desenterraron los cimientos para repartirse la casa. Lo único que para nadie pasó inadvertido en el fragor de aquel entierro, fue el estruendoso suspiro de descanso que exhalaron las muchedumbres cuando se cumplieron los catorce días de plegarias, exaltaciones y ditirambos, y la tumba fue sellada con una plataforma de plomo. Algunos de los allí presentes dispusieron de la suficiente clarividencia para comprender que estaban asistiendo al nacimiento de una nueva época. Ahora podía el sumo pontífice subir al Cielo en cuerpo y alma, cumplida su misión en la tierra, y podía el presidente de la república sentarse a gobernar según su buen criterio, y podían las reinas de todo lo habido y por haber casarse y ser felices y engendrar y parir muchos hijos, y podían las muchedumbres colgar sus toldos según su leal modo de saber y entender en los desmesurados dominios de la Mamá Grande, porque la única que podía oponerse a ello y tenía suficiente poder para hacerlo había empezado a pudrirse bajo una plataforma de plomo. Solo faltaba entonces que alguien recostara un taburete en la puerta para contar esta historia, lección y escarmiento de las generaciones futuras, y que ninguno de los incrédulos del mundo se quedara sin conocer la noticia de la Mamá Grande, que mañana miércoles vendrán los barrenderos y barrerán la basura de sus funerales, por todos los siglos de los siglos.
"""

marquez_docs = marquez_raw.split(". ")
